e_commerce/e_commerce/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('home.urls', namespace='home')),
    path('accounts/', include('account.urls', namespace='account')),
    path('orders/', include('orders.urls', namespace='orders')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

e_commerce/home/urls.py
from django.urls import path
from . import views

app_name = 'home'

urlpatterns = [
    path('', views.HomeView.as_view(), name='home'),
    path('category/<slug:category_slug>', views.HomeView.as_view(), name='category_filter'),
    path('<slug:slug>/', views.ProductDetailView.as_view(), name='product_detail'),
]

e_commerce/orders/urls.py
from django.urls import path, include
from . import views

app_name = 'orders'

urlpatterns = [
    path('create/', views.OrderCreateView.as_view(), name='order_create'),
	path('detail/<int:order_id>/', views.OrderDetailView.as_view(), name='order_detail'),
	path('cart/', views.CartView.as_view(), name='cart'),
	path('cart/add/<int:product_id>/', views.CartAddView.as_view(), name='cart_add'),
	path('cart/remove/<int:product_id>/', views.CartRemoveView.as_view(), name='cart_remove'),
	# path('pay/<int:order_id>/', views.OrderPayView.as_view(), name='order_pay'),
	# path('verify/', views.OrderVerifyView.as_view(), name='order_verify'),
	path('apply/<int:order_id>/', views.CouponApplyView.as_view(), name='apply_coupon'),
]

e_commerce/home/models.py
from django.db import models
from django.urls import reverse
from ckeditor.fields import RichTextField


class Category(models.Model):
	sub_category = models.ForeignKey('self', on_delete=models.CASCADE, related_name='scategory', null=True, blank=True)
	is_sub = models.BooleanField(default=False)
	name = models.CharField(max_length=200)
	slug = models.SlugField(max_length=200, unique=True)

	class Meta:
		ordering = ('name',)
		verbose_name = 'category'
		verbose_name_plural = 'categories'

	def __str__(self):
		return self.name

	def get_absolute_url(self):
		return reverse('home:category_filter', args=[self.slug,])


class Product(models.Model):
	category = models.ManyToManyField(Category, related_name='products')
	name = models.CharField(max_length=200)
	slug = models.SlugField(max_length=200, unique=True)
	image = models.ImageField()
	# description = RichTextField()
	price = models.IntegerField()
	available = models.BooleanField(default=True)
	created = models.DateTimeField(auto_now_add=True)
	updated = models.DateTimeField(auto_now=True)

	class Meta:
		ordering = ('name',)

	def __str__(self):
		return self.name

	def get_absolute_url(self):
		return reverse('home:product_detail', args=[self.slug,])

e_commerce/home/views.py
from django.shortcuts import render, get_object_or_404
from django.views import View
from .models import Product, Category
from orders.forms import CartAddForm
# Create your views here.
class HomeView(View):
	def get(self, request, category_slug=None):
		products = Product.objects.filter(available=True)
		categories = Category.objects.filter(is_sub=False)
		if category_slug:
			category = Category.objects.get(slug=category_slug)
			products = products.filter(category=category)
		return render(request, 'home/home.html', {'products':products, 'categories':categories})


class ProductDetailView(View):
	def get(self, request, slug):
		product = get_object_or_404(Product, slug=slug)
		form = CartAddForm()
		return render(request, 'home/detail.html', {'product':product, 'form':form})

e_commerce/home/templates/home/detail.html
{% extends 'base.html' %}

{% block content %}
    <h2>{{ product.name }}</h2>
    <small>{{ product.created }}</small><br/>
    <p>{{ product.price }} Toman</p>
    <img src="{{ product.image.url }}" style="width: 300px;">
    <p>{{ product.description|safe }}</p><br/><br/>

    <form action="{% url 'orders:cart_add' product.id %}" method="post">
        {% csrf_token %}
        {{ form }}
        <input type="submit" value="add to cart">
    </form>
{% endblock %}

e_commerce/home/templates/home/home.html
{% extends 'base.html' %}
{% load static %}

{% block extra_headers %}
<link rel="stylesheet" href="{% static 'home/css/style.css' %}">
{% endblock %}

{% block content %}

  <div class="row">
    {% for category in categories %}
      <div class="col-md-3 col-sm-6">
        <div class="btn-group">
          <a href="{{ category.get_absolute_url }}" class="btn btn-danger">{{ category.name }}</a>
          <button type="button" class="btn btn-danger dropdown-toggle dropdown-toggle-split" data-bs-toggle="dropdown" aria-expanded="false">
            <span class="visually-hidden">Toggle Dropdown</span>
          </button>
          <ul class="dropdown-menu">
            {% for sub in category.scategory.all %}
              <li><a class="dropdown-item" href="{{ sub.get_absolute_url }}">{{ sub.name }}</a></li>
            {% endfor %}
          </ul>
        </div>
      </div>
    {% endfor %}
  </div>

  <div class="row">
    {% for product in products %}
      <div class="col-md-3 col-sm-6">
        <div class="card">
          <img src="{{ product.image.url }}" class="card-img-top">
          <div class="card-body">
            <a href="{{ product.get_absolute_url }}" class="card-title">{{ product.name }}</a>
          </div>
        </div>
      </div>
    {% endfor %}
  </div>

{% endblock %}